# This configuration file contains the custom configurations parameters
# for the CI workflow to run with the example data.
builds:
  - genome/global
  - N450/global

inputs:
    - name: example_data
      metadata: example_data/metadata.tsv
      sequences: example_data/sequences.fasta

subsample:
    genome/global:
        samples:
            early:
                min_date: 1950
                max_date: 2017
            late:
                min_date: 2017
    N450/global:
        samples:
            early:
                min_date: 1950
                max_date: 2017
            late:
                min_date: 2017
