builds: ['genome', 'N450', 'north-america']
strain_id_field: "accession"
inputs:
  - name: ppx_open
    metadata: "s3://nextstrain-data/files/workflows/measles/metadata.tsv.zst"
    sequences: "s3://nextstrain-data/files/workflows/measles/sequences.fasta.zst"

files:
    reference: "measles_reference_{gene_or_genome}.gb"
    reference_fasta: "measles_reference_{gene_or_genome}.fasta"
    colors: "colors.tsv"
    auspice_config: "auspice_config_{build}.json"
    description: "description.md"

# While 'build' is the canonical dataset wildcard, the initial steps of the
# pipeline can be shared between multiple builds for performance reasons.
# This lookup links the {build} wildcard to a {gene_or_genome} wildcard
# which is used for nextclade alignment & min-length filtering, as well as
# which references are used
build_to_gene_or_genome:
  N450: N450
  genome: genome
  north-america: genome

nextclade:
  # key represents {gene_or_genome} wildcard
  genome: >-
      --min-seed-cover 0.01
      --min-length 5000
      --silent
  N450: >-
      --min-seed-cover 0.01
      --min-length 400
      --silent

subsample:
    genome:
        samples:
            early:
                max_sequences: 2000
                min_date: 1950
                max_date: 5Y
                min_length: 5000
                group_by:
                    - country
                    - year
                include: include_strains_genome.txt
                exclude: dropped_strains.txt
            late:
                max_sequences: 2000
                min_date: 5Y
                min_length: 5000
                group_by:
                    - country
                    - year
                include: include_strains_genome.txt
                exclude: dropped_strains.txt
    north-america:
        samples:
            late:
                max_sequences: 2000
                min_date: "2025-01-01"
                min_length: 5000
                group_by:
                    - division
                    - year
                exclude_where:
                    - "genotype_ppx!=D8"
                    - "region!=North America"
                include: include_strains_north-america.txt
                exclude: dropped_strains.txt
    N450:
        samples:
            early:
                max_sequences: 2000
                min_date: 1950
                max_date: 5Y
                min_length: 400
                group_by:
                    - country
                    - year
                include: include_strains_N450.txt
                exclude: dropped_strains.txt
            late:
                max_sequences: 2000
                min_date: 5Y
                min_length: 400
                group_by:
                    - country
                    - year
                include: include_strains_N450.txt
                exclude: dropped_strains.txt
refine:
    genome: >-
        --timetree
        --coalescent opt
        --date-inference marginal
        --date-confidence
        --clock-filter-iqd 8
        --stochastic-resolve
        --divergence-units mutations-per-site
    north-america: >-
        --timetree
        --coalescent opt
        --date-inference marginal
        --date-confidence
        --clock-filter-iqd 8
        --clock-rate 0.000425
        --root PP_003QHNN
        --stochastic-resolve
        --divergence-units mutations-per-site
    N450: >-
        --timetree
        --coalescent opt
        --date-inference marginal
        --date-confidence
        --clock-filter-iqd 4
        --stochastic-resolve
        --divergence-units mutations-per-site


ancestral:
    inference: "joint"

# per-build traits. If you wish traits to be skipped you must use a `False` value
# (to avoid accidentally forgetting to fill out this part of the config)
traits:
    genome:
        columns:
            - country
            - region
        sampling_bias_correction: 3
    north-america:
        columns:
            - division
        sampling_bias_correction: 3
    N450: False


tip_frequencies:
    min_date: "2000-01-01"
    max_date: "6M"
    narrow_bandwidth: 0.2
    wide_bandwidth: 0.6

export:
    genome: &general_export
        metadata_columns: "strain division location dataUseTerms restrictedUntil PPX_accession INSDC_accession"
    north-america:
      <<: *general_export
    N450:
      <<: *general_export
