name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    uses: nextstrain/.github/.github/workflows/pathogen-repo-ci.yaml@master

  nextstrain_run:
    runs-on: ubuntu-latest
    env:
      EXAMPLE_DIR: phylogenetic/custom-analyses/north-america-outbreak-example/
      ANALYSIS_DIR: analysis-directory/
    steps:
      - uses: nextstrain/.github/actions/setup-nextstrain-cli@master

      - name: Setup pathogen
        run: nextstrain setup measles@${{ github.sha }}

      - name: Checkout analysis directory
        uses: actions/checkout@v7
        with:
          ref: ${{ github.sha }}
          sparse-checkout-cone-mode: false
          sparse-checkout: ${{ env.EXAMPLE_DIR }}
          path: ${{ env.ANALYSIS_DIR }}

      - name: Setup analysis directory
        run: |
          mv ${{ env.ANALYSIS_DIR }}${{ env.EXAMPLE_DIR }}* ${{ env.ANALYSIS_DIR }}

        # TODO: run other workflows
      - name: Run phylo example
        run: nextstrain run measles@${{ github.sha }} phylogenetic ${{ env.ANALYSIS_DIR }}
